workflows:
  ios-workflow:
    name: iOS Flutter Build (SideStore)
    max_build_duration: 60

    environment:
      flutter: stable

    scripts:
      - name: Get dependencies
        script: flutter pub get

      - name: Clean build
        script: flutter clean

      - name: Build iOS
        script: flutter build ios --release --no-codesign

      - name: Create IPA manually
        script: |
          set -e

          mkdir -p build/ios/ipa

          cd build/ios/iphoneos

          rm -rf Payload
          mkdir Payload
          cp -r Runner.app Payload/

          zip -r App.ipa Payload

          mv App.ipa ../../ipa/

    artifacts:
      - build/ios/ipa/*.ipa